name: Python Tests Matrix
permissions:
  contents: read

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - '.github/workflows/**'
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - '.github/workflows/**'
  workflow_dispatch:

jobs:
  linux-tests:
    strategy:
      matrix:
        backend: [fulcrum, cbf]
    uses: ./.github/workflows/python-tests.yml
    secrets: inherit
    with:
      os: ubuntu-22.04
      backend: ${{ matrix.backend }}

  windows-tests:
    if: ${{ github.event_name == 'pull_request' && contains(github.event.pull_request.labels.*.name, 'pytest-win') }}
    strategy:
      matrix:
        backend: [cbf]
    uses: ./.github/workflows/python-tests.yml
    secrets: inherit
    with:
      os: windows-latest
      backend: ${{ matrix.backend }}
