name: Python Tests Matrix
permissions:
  contents: read

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  linux-tests:
    if: >
      github.event_name != 'pull_request' ||
      !(
        github.event.pull_request.user.login == 'weblate' &&
        github.event.pull_request.head.repo.full_name == 'weblate/bitcoin-safe'
      )
    strategy:
      matrix:
        backend: [fulcrum, cbf]
    uses: ./.github/workflows/python-tests.yml
    secrets: inherit
    with:
      os: ubuntu-22.04
      backend: ${{ matrix.backend }}

  windows-tests:
    if: >
      github.event_name == 'pull_request' &&
      contains(github.event.pull_request.labels.*.name, 'pytest-win') &&
      !(
        github.event.pull_request.user.login == 'weblate' &&
        github.event.pull_request.head.repo.full_name == 'weblate/bitcoin-safe'
      )
    strategy:
      matrix:
        backend: [cbf]
    uses: ./.github/workflows/python-tests.yml
    secrets: inherit
    with:
      os: windows-latest
      backend: ${{ matrix.backend }}
